### ISSUE TITLE
Calculations for grs80 to latlng

### ISSUE THREAD

**Issue by grayhare** [dvdoug/PHPCoord#13]
I'm trying to convert a shapefile and used the prj file as basis but the latlng coordinates are wrong, am I using the class correctly? I pasted a short version of the class.

PRJ https://gist.github.com/anonymous/6dd1ed02c2976374dd1e42fc8628e317
PHP https://gist.github.com/anonymous/27da56ce310d896c81083e1f496074c2

**Comment by dvdoug** [comment]
Hello

Can you supply a couple of examples of the input coordinates you're using and your expected output?

**Comment by grayhare** [comment]
Hello, thank you for responding. Here is a point from the shapefile.

X Y 441585.5381, 1508073.406
Expected latlng 34.64302821594152,-86.54699921607971
Calculated latlng 44.05728,-88.51135

**Comment by dvdoug** [comment]
Hello

Your issue is one of units - the grid co-ordinates are in feet, but the definitions of the ellipsoids are in meters. See sample code which does the conversion.

After conversion, the output from the library matches https://epsg.io/transform#s_srs=102629&t_srs=4326&x=441443.6833000&y=1507674.1487000 to the first 5dp (approx 1m) where the output is rounded to.

**Comment by grayhare** [comment]
I appreciate your help, Doug. Cheers
