### ISSUE TITLE
Irish Grid to WGS84 problems

### ISSUE THREAD

**Issue by mrjose** [dvdoug/PHPCoord#25]
Hi,

There appears to be an issue with the conversion from Irish Grid to WGS84.
Given the following code:

`$coord = new IrishGridRef(322364.659, 226034.372);`
`$newCoords = $coord->toLatLng()->toWGS84();`

I would expect to see the following Lat & Lng:

`lat: 53.270753`
`lng: -6.1663770`

Instead I get the following:

`lat: 53.27059696595`
`lng: -6.1670186227361`

This is over 40 meters off what is expected.
As reference I am using https://irish.gridreferencefinder.com/ which appears to accurately plot all of the positions I am entering with Irish Grid and ITM.

Any ideas what could be the problem here?

Many thanks!

**Comment by mrjose** [comment]
Further to this, the MyGeodata Cloud website is generating better results: https://mygeodata.cloud/cs2cs/

This is a conversion from TM75 Irish Grid to WGS84. The output in this case:

`lat: 53.2707817373`
`lng: -6.16661198943`

**Comment by dvdoug** [comment]
Interesting...

The main reason for the discrepency appears to be the values converting Irish Grid to WGS84 I took from an OSI document here: https://www.osi.ie/wp-content/uploads/2015/07/Survey-Ireland-1999-Making-Maps-Compatible-with-GPS.pdf?ext=.pdf

If you look at slide 28, the 3 rotation parameters are expressed as postive numbers (they even include the `+`).

If you look at the params from `MyGeoData`, they are negative versions of the same numbers. When I flip the signs on `MyGeoData` and also adjust the other params to be the 3dp rather than 1dp versions, the numbers are basically the same.

**Comment by dvdoug** [comment]
So question is which way around are the rotations supposed to be - does the official document I've used as source have a mistake?

**Comment by dvdoug** [comment]
Fix coming up shortly

**Comment by dvdoug** [comment]
Thanks for reporting this @mrjose

**Comment by mrjose** [comment]
Thanks @dvdoug the update appears to have worked a treat!
