### ISSUE TITLE
Library upgrade assistance

### ISSUE THREAD

**Issue by imbeingfollowed** [dvdoug/PHPCoord#28]
Hi,

Wondering if you can help. I'm a long time user and need to upgrade as the old version is no longer compatible with PHP 8.

It looks like the library has grown a few arms and legs since and I'm a bit confused with all the classes and datum so please excuse my ignorance. This is how far I managed to get:

------ Old usage:

require "phpcoord-2.3.php";

$os = new OSRef(199800, 554200);
$ll = $os->toLatLng();
echo $ll->lat . " " . $ll->lng;

------ New attempt:

require "vendor/autoload.php";

use PHPCoord\CoordinateReferenceSystem\Projected;
use PHPCoord\ProjectedPoint;
use PHPCoord\UnitOfMeasure\Length\Metre;
use PHPCoord\CoordinateReferenceSystem\Geographic2D;

$from = ProjectedPoint::createFromEastingNorthing(
	new Metre(554200),
	new Metre(199800),
	Projected::fromSRID(Projected::EPSG_OSGB_1936_BRITISH_NATIONAL_GRID)
);

$to = $from->asGeographicPoint();
echo $to->getLatitude() . " " . $to->getLongitude();

**Comment by dvdoug** [comment]
Yes, the original versions were very OSGB36 specific and kinda sorta ignored a lot of (sadly needed) complexity that's required once you expand to different coordinate systems.

```
//Old
$os = new OSRef(199800, 554200);
//New
$from = ProjectedPoint::createFromEastingNorthing(
new Metre(554200),
new Metre(199800),
Projected::fromSRID(Projected::EPSG_OSGB_1936_BRITISH_NATIONAL_GRID)
);
```
This looks right, except that you've reversed the order of coordinates - both old and new are (easting, northing) so you shouldn't need to do that.

From there, you need to explicitly decide which "world model" (datum/ellipsoid) you want your latitude and longitude to use. The older version you're currently using would have assumed you wanted the Airy Ellipsoid (OSGB36). If you actually wanted WGS84 instead, you'd do a followup conversion. Those were the only 2 coordinate systems it supported so that made it easy to use.

```
//Old
$ll = $os->toLatLng(); // assumed OSGB36/Airy Ellipsoid
$ll->OSGB36ToWGS84(); // optional conversion depending on needs

New PHPCoord allows you to convert to many, many different systems so you need to choose up front.

```
//New
$toCRS = Geographic2D::fromSRID(Geographic2D::EPSG_OSGB_1936);
//or
$toCRS = Geographic2D::fromSRID(Geographic2D::EPSG_WGS_84);
$to = $from->convert($toCRS);
echo $to->getLatitude() . " " . $to->getLongitude();
```

Hope that helps?

**Comment by dvdoug** [comment]
See also https://www.phpcoord.net/en/stable/creating_points_projected.html#british-national-grid if you need to work with grid letters

**Comment by imbeingfollowed** [comment]
Cheers for your help Doug - with your kind notes and a fresh head this morning I was able to tackle it.

You were correct - I was converting a grid ref to Easting & Northings prior to that step as I don't think the library supported that at the time. I've removed that step now.

I've kept it as EPSG_OSGB_1936 too as it has always seemed to work for me when used with Google Maps. Maybe someone knows any different.

Here's my final code in case it helps anyone.

$point = BritishNationalGridPoint::fromGridReference('TQ 30017 80419');
$toCRS = Geographic2D::fromSRID(Geographic2D::EPSG_OSGB_1936);
$to = $point->convert($toCRS);
$start_lat = floatval((string) $to->getLatitude());
$start_lng = floatval((string) $to->getLongitude());


Thanks again.
