### ISSUE TITLE
Unable to perform conversion

### ISSUE THREAD

**Issue by DMGPage** [dvdoug/PHPCoord#59]
I have quite a lot Estonian addresses and their x, y coordinates. And I'm trying to get from them lat, long coordinates. But for some reason around 4000 addresses throws error: "Unable to perform conversion, please file a bug if you think this is incorrect".

Here's my code example:
```          
 $srcPoint = ProjectedPoint::createFromEastingNorthing(
      new Metre($x_coordinate), // example: 738480.02
      new Metre($y_coordinate), // example: 6588088.08
      Projected::fromSRID(Projected::EPSG_ESTONIAN_COORDINATE_SYSTEM_OF_1997)
  );
  $toCRS = Geographic2D::fromSRID(Geographic2D::EPSG_WGS_84);
  $dstPoint = $srcPoint->convert($toCRS);

  $latitude = $dstPoint->getLatitude();
  $longitude = $dstPoint->getLongitude();
```

I'm using version 4.7.0, because this project is stuck with old php 7 version.
I tried online x, y transformation and that should work just fine: https://epsg.io/transform#s_srs=3301&t_srs=4326&x=738480.0200000&y=6588088.0800000

**Comment by dvdoug** [comment]
Hi @DMGPage

The problem here is that the EPSG-defined extent/boundary for Estonia is apparently wrong on the eastern-most border of Estonia and your example point is outside of it. That's the why the conversion is failing, PHPCoord is objecting that the conversion you're asking for is invalid because it thinks the point isn't in Estonia (see attached map).

If you tweak your code to use `$dstPoint = $srcPoint->convert($toCRS, true);` then it should work. That second parameter will tell PHPCoord to ignore the map validation error.

![image](https://github.com/dvdoug/PHPCoord/assets/1571110/95f2ad56-d8ed-4ff8-9025-73b488af3972)
